//! Reading file contents safely.

use std::fs::File;
use std::io::Read;
use std::path::Path;

use repodna_core::hash::{sha256, to_hex};

/// Number of leading bytes inspected for NUL bytes, matching Git's binary heuristic.
const BINARY_SNIFF_BYTES: usize = 8_000;

/// The content of a file that was read successfully.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileContent {
    /// Size in bytes.
    pub bytes: u64,
    /// `true` when the file contains NUL bytes in its first 8,000 bytes.
    pub binary: bool,
    /// Decoded text (invalid UTF-8 is replaced), absent for binary files.
    pub text: Option<String>,
    /// Full SHA-256 of the raw bytes.
    pub sha256: [u8; 32],
}

impl FileContent {
    /// First 16 hexadecimal characters of the SHA-256 digest, as stored in artifacts.
    pub fn short_hash(&self) -> String {
        to_hex(&self.sha256[..8])
    }

    /// Full hexadecimal SHA-256 digest, used as a cache key.
    pub fn hash_hex(&self) -> String {
        to_hex(&self.sha256)
    }

    /// The first line of the text, if any (for shebang detection).
    pub fn first_line(&self) -> Option<&str> {
        self.text.as_deref().and_then(|text| text.lines().next())
    }
}

/// Outcome of attempting to read a file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReadOutcome {
    /// The file was read.
    Content(FileContent),
    /// The file exceeds the size limit and was not read.
    TooLarge {
        /// Size in bytes.
        bytes: u64,
    },
    /// The file could not be read.
    Unreadable(String),
}

/// Returns `true` when `bytes` look binary (contain a NUL byte near the start).
pub fn looks_binary(bytes: &[u8]) -> bool {
    bytes[..bytes.len().min(BINARY_SNIFF_BYTES)].contains(&0)
}

/// Reads a file of at most `max_bytes` bytes.
///
/// Symbolic links are never followed: callers pass paths produced by the walker, which
/// reports links separately, and the file type is re-checked here before opening.
pub fn read_file(path: &Path, max_bytes: u64) -> ReadOutcome {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) => return ReadOutcome::Unreadable(error.to_string()),
    };
    if !metadata.file_type().is_file() {
        return ReadOutcome::Unreadable("not a regular file".to_owned());
    }
    if metadata.len() > max_bytes {
        return ReadOutcome::TooLarge {
            bytes: metadata.len(),
        };
    }
    let mut buffer = Vec::with_capacity(usize::try_from(metadata.len()).unwrap_or(0));
    let read = File::open(path).and_then(|file| {
        // Never read beyond the limit, even if the file grew after the metadata check.
        file.take(max_bytes + 1).read_to_end(&mut buffer)
    });
    if let Err(error) = read {
        return ReadOutcome::Unreadable(error.to_string());
    }
    if buffer.len() as u64 > max_bytes {
        return ReadOutcome::TooLarge {
            bytes: buffer.len() as u64,
        };
    }
    ReadOutcome::Content(content_from_bytes(&buffer))
}

/// Builds [`FileContent`] from raw bytes.
pub fn content_from_bytes(bytes: &[u8]) -> FileContent {
    let binary = looks_binary(bytes);
    let text = if binary {
        None
    } else {
        let without_bom = bytes.strip_prefix(&[0xef, 0xbb, 0xbf]).unwrap_or(bytes);
        Some(String::from_utf8_lossy(without_bom).into_owned())
    };
    FileContent {
        bytes: bytes.len() as u64,
        binary,
        text,
        sha256: sha256(bytes),
    }
}

/// Header phrases that mark a file as machine-generated. Matched case-insensitively
/// within the first lines of a file.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "code generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "this file is generated",
    "this file was generated",
    "generated by the protocol buffer compiler",
];

/// Returns `true` when the text carries a generated-code header or looks minified.
///
/// Checks the first five lines for conventional markers (such as Go's
/// `// Code generated … DO NOT EDIT.`), and treats JavaScript or CSS with an extremely
/// long line as minified output.
pub fn looks_generated(text: &str, language: Option<&str>) -> bool {
    let header: String = text
        .lines()
        .take(5)
        .collect::<Vec<_>>()
        .join("\n")
        .to_ascii_lowercase();
    if GENERATED_MARKERS
        .iter()
        .any(|marker| header.contains(marker))
    {
        return true;
    }
    if matches!(language, Some("javascript" | "css" | "scss" | "less")) {
        return text.lines().take(50).any(|line| line.len() > 3_000);
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_binary_content() {
        assert!(looks_binary(b"\x89PNG\r\n\x1a\n\0\0"));
        assert!(!looks_binary(b"plain text\n"));
        let content = content_from_bytes(b"abc\0def");
        assert!(content.binary);
        assert!(content.text.is_none());
    }

    #[test]
    fn decodes_text_and_strips_the_bom() {
        let content = content_from_bytes(b"\xef\xbb\xbf#!/bin/sh\necho hi\n");
        assert_eq!(content.first_line(), Some("#!/bin/sh"));
        assert_eq!(content.bytes, 21);
        assert_eq!(content.short_hash().len(), 16);
        assert_eq!(content.hash_hex().len(), 64);
        let lossy = content_from_bytes(b"caf\xe9\n");
        assert!(lossy.text.unwrap().starts_with("caf"));
    }

    #[test]
    fn reads_files_within_limits() {
        let dir = tempfile::tempdir().unwrap();
        let small = dir.path().join("small.txt");
        std::fs::write(&small, "hello").unwrap();
        match read_file(&small, 1024) {
            ReadOutcome::Content(content) => assert_eq!(content.text.as_deref(), Some("hello")),
            other => panic!("unexpected {other:?}"),
        }
        assert_eq!(read_file(&small, 3), ReadOutcome::TooLarge { bytes: 5 });
        assert!(matches!(
            read_file(&dir.path().join("missing"), 10),
            ReadOutcome::Unreadable(_)
        ));
        assert!(matches!(
            read_file(dir.path(), 10),
            ReadOutcome::Unreadable(_)
        ));
    }

    #[cfg(unix)]
    #[test]
    fn does_not_follow_symlinks() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("target.txt");
        std::fs::write(&target, "secret").unwrap();
        let link = dir.path().join("link.txt");
        std::os::unix::fs::symlink(&target, &link).unwrap();
        assert!(matches!(read_file(&link, 1024), ReadOutcome::Unreadable(_)));
    }

    #[test]
    fn recognizes_generated_headers_and_minified_code() {
        assert!(looks_generated(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
            Some("go")
        ));
        assert!(looks_generated("/* @generated */\n", Some("javascript")));
        assert!(looks_generated(&"a".repeat(4_000), Some("javascript")));
        assert!(!looks_generated(&"a".repeat(4_000), Some("rust")));
        assert!(!looks_generated("fn main() {}\n", Some("rust")));
        let late = format!("{}// Code generated\n", "x\n".repeat(10));
        assert!(
            !looks_generated(&late, Some("go")),
            "only the header is checked"
        );
    }
}
