//! Markdown and terminal renderings of an explanation. Model text is always escaped so it
//! cannot inject markup or terminal control sequences.

use crate::explain::Explanation;
use crate::response::Support;

/// Project URL shown in the footer.
const PROJECT_URL: &str = "https://github.com/sanskarIN/RepoDNA";

/// Escapes Markdown and HTML metacharacters in inline text.
fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '\\' | '`' | '*' | '_' | '[' | ']' | '#' | '|' | '~' => {
                out.push('\\');
                out.push(c);
            }
            '\n' => out.push(' '),
            _ => out.push(c),
        }
    }
    out
}

/// Wraps text in a code span that its own backticks cannot close.
fn code(text: &str) -> String {
    let longest = text.split(|c| c != '`').map(str::len).max().unwrap_or(0);
    let fence = "`".repeat(longest + 1);
    let pad = if text.starts_with('`') || text.ends_with('`') {
        " "
    } else {
        ""
    };
    format!("{fence}{pad}{}{pad}{fence}", text.replace('\n', " "))
}

fn usage_line(e: &Explanation) -> String {
    let u = &e.usage;
    let kind = if u.tokens_estimated {
        "estimated"
    } else {
        "reported by the provider"
    };
    let output = u
        .output_tokens
        .map_or_else(|| "not reported".to_owned(), |n| n.to_string());
    let cost = u.estimated_cost.map_or_else(
        || "not estimated (no prices configured)".to_owned(),
        |cost| format!("{cost:.4} in the currency of your configured prices"),
    );
    format!(
        "Tokens ({kind}): {} input, {output} output. Cost: {cost}.",
        u.input_tokens
    )
}

fn context_line(e: &Explanation) -> String {
    let mut line = format!("{} evidence items were sent", e.evidence_sent);
    if e.evidence_omitted > 0 {
        line.push_str(&format!(
            " ({} more were left out to fit the context budget)",
            e.evidence_omitted
        ));
    }
    line.push_str(if e.excerpts_sent {
        "; redacted source excerpts were included."
    } else {
        "; no source code was sent."
    });
    line
}

fn revision(e: &Explanation) -> String {
    e.revision.as_deref().map_or_else(
        || "unknown revision".to_owned(),
        |r| r.chars().take(12).collect(),
    )
}

/// Renders the explanation as Markdown.
pub fn markdown(e: &Explanation) -> String {
    let a = &e.answer;
    let mut out = format!("# {}\n\n", escape(&e.title));
    out.push_str(&format!("> **AI-generated.** {}\n\n", escape(&e.notice)));
    if let Some(subject) = &e.subject {
        out.push_str(&format!("**Subject:** {}\n\n", code(subject)));
    }
    out.push_str(&format!(
        "**Repository:** {} · revision {} · analyzed {}  \n**Model:** {} / {} ({}) · **Confidence:** {}\n\n",
        escape(&e.repository),
        code(&revision(e)),
        e.analyzed_at.date_string(),
        escape(&e.usage.ai.provider),
        escape(&e.usage.ai.model),
        if e.usage.ai.remote { "remote" } else { "local" },
        a.confidence.label()
    ));
    out.push_str("## Summary\n\n");
    out.push_str(&escape(&a.summary));
    out.push_str("\n\n");
    if !a.points.is_empty() {
        out.push_str("## Points\n\n");
        for (index, point) in a.points.iter().enumerate() {
            let cites = if point.evidence.is_empty() {
                String::new()
            } else {
                format!(" [{}]", point.evidence.join(", "))
            };
            let label = match point.support {
                Support::Evidence => String::new(),
                other => format!(" — *{}*", other.label()),
            };
            out.push_str(&format!(
                "{}. {}{cites}{label}\n",
                index + 1,
                escape(&point.text)
            ));
        }
        out.push('\n');
    }
    if !e.evidence.is_empty() {
        out.push_str("## Evidence cited\n\n");
        for item in &e.evidence {
            out.push_str(&format!(
                "- **{}** · {} · {} — {}\n",
                item.id,
                item.kind.label(),
                code(&item.reference),
                escape(&item.detail)
            ));
        }
        out.push('\n');
    }
    if !a.limitations.is_empty() {
        out.push_str("## Limitations\n\n");
        for limitation in &a.limitations {
            out.push_str(&format!("- {}\n", escape(limitation)));
        }
        out.push('\n');
    }
    out.push_str(&format!(
        "---\n\n{} {}\n\nGenerated by RepoDNA {} on {} · {PROJECT_URL}\n",
        context_line(e),
        usage_line(e),
        e.tool_version,
        e.generated_at.date_string()
    ));
    out
}

/// Renders the explanation as plain text for a terminal.
pub fn text(e: &Explanation) -> String {
    let a = &e.answer;
    let mut out = format!("{} (AI-generated)\n", e.title);
    out.push_str(&format!(
        "{} · revision {} · {} / {} ({}) · confidence {}\n\n",
        e.repository,
        revision(e),
        e.usage.ai.provider,
        e.usage.ai.model,
        if e.usage.ai.remote { "remote" } else { "local" },
        a.confidence.label()
    ));
    out.push_str(&a.summary);
    out.push_str("\n\n");
    for (index, point) in a.points.iter().enumerate() {
        out.push_str(&format!("{:>2}. {}\n", index + 1, point.text));
        let references: Vec<String> = point
            .evidence
            .iter()
            .filter_map(|id| e.evidence.iter().find(|item| &item.id == id))
            .map(|item| format!("{} {}", item.id, item.reference))
            .collect();
        if !references.is_empty() {
            out.push_str(&format!("    evidence: {}\n", references.join("; ")));
        }
        if point.support != Support::Evidence {
            out.push_str(&format!("    ({})\n", point.support.label()));
        }
    }
    if !a.limitations.is_empty() {
        out.push_str("\nLimitations:\n");
        for limitation in &a.limitations {
            out.push_str(&format!("  - {limitation}\n"));
        }
    }
    out.push_str(&format!(
        "\n{}\n{}\n{}\n",
        e.notice,
        context_line(e),
        usage_line(e)
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::explain::tests::explained;

    #[test]
    fn renders_markdown_with_labels_and_escaping() {
        let mut explanation = explained();
        explanation.answer.summary = "Uses <script>alert(1)</script> and *stars*".into();
        let md = markdown(&explanation);
        assert!(md.starts_with("# Repository explanation\n"));
        assert!(md.contains("> **AI-generated.**"));
        assert!(md.contains("&lt;script&gt;"));
        assert!(md.contains("\\*stars\\*"));
        assert!(md.contains("1. Networking code lives in src/net. [E1, E3]\n"));
        assert!(md.contains("model inference, not established by the analysis"));
        assert!(md.contains("## Evidence cited"));
        assert!(md.contains("**E3** · module · `src/net`"));
        assert!(md.contains("No tests were described."));
        assert!(md.contains("no source code was sent"));
        assert!(md.contains("Tokens (estimated)"));
        assert!(md.contains(PROJECT_URL));
    }

    #[test]
    fn renders_terminal_text() {
        let out = text(&explained());
        assert!(out.starts_with("Repository explanation (AI-generated)\n"));
        assert!(out.contains("    evidence: E1 identity; E3 src/net\n"));
        assert!(out.contains("(model inference, not established by the analysis)"));
        assert!(out.contains("Limitations:\n  - No tests were described."));
    }

    #[test]
    fn code_spans_survive_backticks() {
        assert_eq!(code("a`b"), "``a`b``");
        assert_eq!(code("`x"), "`` `x ``");
        assert_eq!(escape("a|b\nc"), "a\\|b c");
    }
}
