//! Cover, executive summary, identity, languages, and structure.

use repodna_core::model::artifact::RepositoryDna;
use repodna_core::model::evolution::StatementKind;
use repodna_core::model::languages::LanguageKind;
use repodna_core::model::structure::EntrypointKind;
use repodna_core::severity::Severity;

use super::{ContentOptions, confidence, heading, not_analyzed, notes};
use crate::card::{CardOptions, render_facts};
use crate::charts::{Share, share_bar, treemap};
use crate::doc::{Blocks, Inline, Table, code, plain};
use crate::facts::{Facts, facts, folded_languages};
use crate::sections::Section;
use crate::text::{bytes, list, percent, span, thousands};

fn optional(value: Option<u64>) -> String {
    value.map_or_else(|| "Not analyzed".to_owned(), thousands)
}

fn headline_stats(facts: &Facts) -> Vec<(String, String)> {
    vec![
        ("Files".to_owned(), thousands(facts.files)),
        ("Code lines".to_owned(), thousands(facts.code_lines)),
        ("Commits".to_owned(), optional(facts.commits)),
        ("Contributors".to_owned(), optional(facts.contributors)),
        (
            "History".to_owned(),
            facts
                .age_days
                .map_or_else(|| "Not analyzed".to_owned(), span),
        ),
        (
            "Direct dependencies".to_owned(),
            optional(facts.dependencies),
        ),
    ]
}

pub(super) fn cover(blocks: &mut Blocks, dna: &RepositoryDna, options: ContentOptions) {
    let facts = facts(dna);
    blocks.heading(1, format!("{} — Project DNA", facts.name), Some("cover"));
    if let Some(description) = &facts.description {
        blocks.text(description.clone());
    }
    let mut line = vec![Inline::Text(format!(
        "Generated by RepoDNA {} on {}",
        dna.tool.version,
        dna.analysis_metadata.generated_at.date_string()
    ))];
    if let Some(revision) = &facts.revision {
        line.push(Inline::Text(" from revision ".to_owned()));
        line.push(Inline::Code(revision.clone()));
    }
    line.push(Inline::Text(format!(
        " with the {} profile.",
        dna.analysis_metadata.profile
    )));
    blocks.rich(line);
    if options.figures {
        blocks.figure(
            Some(render_facts(
                &facts,
                CardOptions {
                    dark: options.dark,
                    branding: options.branding,
                },
            )),
            "Project DNA card",
        );
    }
    let mut stats = headline_stats(&facts);
    if !facts.dna_hash.is_empty() {
        stats.push(("DNA hash".to_owned(), facts.dna_hash.clone()));
    }
    blocks.stats(stats);
}

pub(super) fn summary(blocks: &mut Blocks, dna: &RepositoryDna) {
    heading(blocks, Section::Summary);
    let facts = facts(dna);
    let languages: Vec<String> = facts
        .languages
        .iter()
        .take(3)
        .map(|l| format!("{} ({})", l.name, percent(l.share)))
        .collect();
    let mut overview = format!(
        "{} is a {} repository with {} files and {} code lines",
        facts.name,
        dna.structure.size_class.label().to_lowercase(),
        thousands(facts.files),
        thousands(facts.code_lines)
    );
    if languages.is_empty() {
        overview.push('.');
    } else {
        overview.push_str(&format!(", written mainly in {}.", list(&languages)));
    }
    if let (Some(commits), Some(contributors), Some(days)) =
        (facts.commits, facts.contributors, facts.age_days)
    {
        overview.push_str(&format!(
            " Its history spans {} with {} commit{} by {} contributor {}.",
            span(days),
            thousands(commits),
            if commits == 1 { "" } else { "s" },
            thousands(contributors),
            if contributors == 1 {
                "identity"
            } else {
                "identities"
            }
        ));
    }
    blocks.text(overview);
    let counts = dna.finding_counts();
    blocks.stats(vec![
        ("Critical".to_owned(), counts.critical.to_string()),
        ("Warnings".to_owned(), counts.warning.to_string()),
        ("Attention".to_owned(), counts.attention.to_string()),
        ("Informational".to_owned(), counts.info.to_string()),
        ("Suppressed".to_owned(), counts.suppressed.to_string()),
    ]);
    if !dna.insights.first_look.is_empty() {
        blocks.heading(3, "First look", None);
        blocks.list(
            dna.insights
                .first_look
                .iter()
                .map(|answer| {
                    let kind = match answer.kind {
                        StatementKind::Fact => "fact",
                        StatementKind::Interpretation => "interpretation",
                    };
                    vec![
                        Inline::Strong(answer.question.clone()),
                        Inline::Text(format!(
                            " {} ({kind}, {} confidence)",
                            answer.answer,
                            answer.confidence.label().to_lowercase()
                        )),
                    ]
                })
                .collect(),
        );
    }
    let urgent: Vec<_> = dna
        .findings
        .iter()
        .filter(|f| !f.is_suppressed() && f.severity >= Severity::Attention)
        .take(5)
        .collect();
    if !urgent.is_empty() {
        blocks.heading(3, "Look at first", None);
        blocks.list(
            urgent
                .iter()
                .map(|f| {
                    vec![
                        Inline::Strong(f.severity.label().to_owned()),
                        Inline::Text(format!(": {}", f.title)),
                    ]
                })
                .collect(),
        );
    }
    blocks.note("Findings are analysis signals backed by evidence, not formal guarantees. Severity follows documented criteria; see the findings section for the evidence and limitations of each.");
}

pub(super) fn identity(blocks: &mut Blocks, dna: &RepositoryDna) {
    heading(blocks, Section::Identity);
    let identity = &dna.identity;
    let mut table = Table::new(&["Property", "Value"]);
    let mut row = |label: &str, value: Vec<Inline>| table.row(vec![plain(label), value]);
    row("Name", plain(identity.name.clone()));
    if let Some(owner) = &identity.owner {
        row("Owner", plain(owner.clone()));
    }
    for remote in &identity.remotes {
        row(&format!("Remote {}", remote.name), code(remote.url.clone()));
    }
    if let Some(branch) = &identity.default_branch {
        row("Default branch", code(branch.clone()));
    }
    if let Some(revision) = &identity.revision {
        row("Revision", code(revision.clone()));
    }
    row(
        "License",
        plain(identity.license.as_ref().map_or_else(
            || "Not detected".to_owned(),
            |license| {
                format!(
                    "{} ({} confidence, from {})",
                    license
                        .spdx
                        .clone()
                        .unwrap_or_else(|| "Unrecognized".to_owned()),
                    license.confidence.label().to_lowercase(),
                    license.path
                )
            },
        )),
    );
    row(
        "Primary languages",
        plain(if identity.primary_languages.is_empty() {
            "None detected".to_owned()
        } else {
            identity.primary_languages.join(", ")
        }),
    );
    if let Some(description) = &identity.description {
        row("Description", plain(description.clone()));
    }
    row(
        "Git repository",
        plain(if identity.is_git_repository {
            "Yes"
        } else {
            "No"
        }),
    );
    row("Size class", plain(identity.size_class.label()));
    blocks.table(table);
}

fn kind_label(kind: LanguageKind) -> &'static str {
    match kind {
        LanguageKind::Programming => "Programming",
        LanguageKind::Markup => "Markup",
        LanguageKind::Stylesheet => "Stylesheet",
        LanguageKind::Data => "Data",
        LanguageKind::Prose => "Prose",
        LanguageKind::Build => "Build",
    }
}

pub(super) fn languages(blocks: &mut Blocks, dna: &RepositoryDna, options: ContentOptions) {
    heading(blocks, Section::Languages);
    let report = &dna.languages;
    if not_analyzed(blocks, report.status, &report.notes) {
        return;
    }
    let facts = facts(dna);
    if options.figures {
        let shares: Vec<Share> = folded_languages(&facts.languages)
            .into_iter()
            .map(|language| Share {
                name: language.name,
                share: language.share,
                slot: language.slot,
            })
            .collect();
        blocks.figure(
            share_bar(&shares, "Share of first-party code by language"),
            "Share of first-party code by language",
        );
    }
    let mut table = Table::new(&[
        "Language",
        "Kind",
        "Files#",
        "Code lines#",
        "Comment lines#",
        "Share#",
        "Analysis",
    ]);
    for language in &report.languages {
        table.row(vec![
            plain(language.name.clone()),
            plain(kind_label(language.kind)),
            plain(thousands(language.files)),
            plain(thousands(language.code_lines)),
            plain(thousands(language.comment_lines)),
            plain(if language.kind.counts_toward_share() {
                percent(language.share)
            } else {
                "–".to_owned()
            }),
            plain(language.capability.label()),
        ]);
    }
    blocks.table(table);
    blocks.note("Shares count first-party code (excluding vendored and generated files) in programming, markup, and stylesheet languages. Data, prose, and build files are listed but not counted. Built-in analysis is lexical: results are heuristic, not compiler-accurate.");
    if report.unrecognized_files > 0 {
        blocks.text(format!(
            "{} text files have no recognized language.",
            thousands(report.unrecognized_files)
        ));
    }
    if !report.interactions.is_empty() {
        blocks.heading(3, "How languages interact", None);
        let mut table = Table::new(&[
            "From",
            "To",
            "Mechanism",
            "Occurrences#",
            "Confidence",
            "Description",
        ]);
        for interaction in &report.interactions {
            table.row(vec![
                plain(interaction.from.clone()),
                plain(interaction.to.clone()),
                plain(interaction.mechanism.clone()),
                plain(thousands(u64::from(interaction.count))),
                plain(confidence(interaction.confidence)),
                plain(interaction.description.clone()),
            ]);
        }
        blocks.table(table);
    }
    notes(blocks, &report.notes);
}

fn entrypoint_kind(kind: EntrypointKind) -> &'static str {
    match kind {
        EntrypointKind::Binary => "Program",
        EntrypointKind::Library => "Library",
        EntrypointKind::Web => "Web",
        EntrypointKind::Cli => "Command line",
        EntrypointKind::Server => "Server",
        EntrypointKind::Script => "Script",
    }
}

pub(super) fn structure(blocks: &mut Blocks, dna: &RepositoryDna, options: ContentOptions) {
    heading(blocks, Section::Structure);
    let report = &dna.structure;
    if not_analyzed(blocks, report.status, &report.notes) {
        return;
    }
    blocks.stats(vec![
        ("Files".to_owned(), thousands(report.total_files)),
        ("Size".to_owned(), bytes(report.total_bytes)),
        ("Lines".to_owned(), thousands(report.total_lines)),
        ("Code lines".to_owned(), thousands(report.code_lines)),
        ("Comment lines".to_owned(), thousands(report.comment_lines)),
        ("Blank lines".to_owned(), thousands(report.blank_lines)),
    ]);
    blocks.heading(3, "File categories", None);
    let mut table = Table::new(&["Category", "Files#", "Size#", "Lines#"]);
    for category in &report.categories {
        table.row(vec![
            plain(category.category.label()),
            plain(thousands(category.files)),
            plain(bytes(category.bytes)),
            plain(thousands(category.lines)),
        ]);
    }
    blocks.table(table);
    let mut top: Vec<_> = report
        .directories
        .iter()
        .filter(|d| d.depth == 1 && d.code_lines > 0)
        .collect();
    top.sort_by(|a, b| {
        b.code_lines
            .cmp(&a.code_lines)
            .then_with(|| a.path.cmp(&b.path))
    });
    if !top.is_empty() {
        blocks.heading(3, "Top-level directories", None);
        if options.figures {
            let items: Vec<(String, f64)> = top
                .iter()
                .take(24)
                .map(|d| (format!("{}/", d.path), d.code_lines as f64))
                .collect();
            blocks.figure(
                treemap(&items, "code lines", "Code lines by top-level directory"),
                "Code lines by top-level directory",
            );
        }
        let mut table = Table::new(&["Directory", "Files#", "Code lines#", "Main language"]);
        let mut rows: Vec<_> = top.clone();
        table.omitted = crate::doc::truncate(&mut rows, 30);
        for directory in rows {
            table.row(vec![
                code(format!("{}/", directory.path)),
                plain(thousands(directory.files)),
                plain(thousands(directory.code_lines)),
                plain(
                    directory
                        .primary_language
                        .clone()
                        .unwrap_or_else(|| "–".to_owned()),
                ),
            ]);
        }
        blocks.table(table);
    }
    blocks.heading(3, "Entrypoints", None);
    if report.entrypoints.is_empty() {
        blocks.text("No entrypoint was detected.");
    } else {
        let mut table = Table::new(&["Path", "Kind", "Language", "Why", "Confidence"]);
        for entry in &report.entrypoints {
            table.row(vec![
                code(entry.path.clone()),
                plain(entrypoint_kind(entry.kind)),
                plain(entry.language.clone().unwrap_or_else(|| "–".to_owned())),
                plain(entry.reason.clone()),
                plain(confidence(entry.confidence)),
            ]);
        }
        blocks.table(table);
    }
    let special = [
        ("generated", report.generated_files),
        ("vendored", report.vendored_files),
        ("binary", report.binary_files),
        ("too large or unreadable", report.skipped_files),
        ("symbolic links (not followed)", report.symlinks),
    ];
    let described: Vec<String> = special
        .iter()
        .filter(|(_, count)| *count > 0)
        .map(|(label, count)| format!("{} {label}", thousands(*count)))
        .collect();
    if !described.is_empty() {
        blocks.text(format!("Special files: {}.", list(&described)));
    }
    notes(blocks, &report.notes);
}

#[cfg(test)]
mod tests {
    use super::super::{ContentOptions, section};
    use crate::markdown::render;
    use crate::sections::Section;
    use repodna_core::model::SectionStatus;
    use repodna_core::model::artifact::RepositoryDna;
    use repodna_core::model::identity::RepositoryIdentity;
    use repodna_core::model::metadata::AnalysisMetadata;

    fn artifact() -> RepositoryDna {
        let mut dna = RepositoryDna::new(
            RepositoryIdentity {
                name: "widget".into(),
                ..RepositoryIdentity::default()
            },
            AnalysisMetadata::default(),
        );
        dna.structure.status = SectionStatus::Analyzed;
        dna.structure.total_files = 3;
        dna.structure.code_lines = 120;
        dna
    }

    #[test]
    fn explains_sections_that_did_not_run() {
        let dna = artifact();
        let markdown = render(&section(
            &dna,
            Section::Languages,
            ContentOptions::default(),
        ));
        assert!(markdown.contains("## Language map"));
        assert!(markdown.contains("> **Not available:** Not analyzed."));
    }

    #[test]
    fn summarizes_without_inventing_history() {
        let dna = artifact();
        let markdown = render(&section(&dna, Section::Summary, ContentOptions::default()));
        assert!(markdown.contains("widget is a tiny repository with 3 files and 120 code lines."));
        assert!(!markdown.contains("history spans"));
        let cover = render(&section(&dna, Section::Cover, ContentOptions::default()));
        assert!(cover.starts_with("# widget — Project DNA"));
        assert!(cover.contains("| Commits | Not analyzed |"));
    }
}
