//! Writing reports and exports without overwriting files RepoDNA did not create.
//!
//! Report bundles go into a directory that RepoDNA marks with a `.repodna-output` file.
//! An existing directory without that marker is used only if it is empty (or with
//! `force`). A single output file replaces an existing file only when that file was
//! generated by RepoDNA (or with `force`). Reports are never written into the root of a
//! Git working tree.

use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use repodna_core::config::ReportTheme;
use repodna_core::io::write_atomic;
use repodna_core::model::artifact::RepositoryDna;
use repodna_report::card::{CardOptions, render as render_card};
use repodna_report::png::render_png;
use repodna_report::{
    CsvTable, GENERATED_MARKER, ReportOptions, csv, html_report, json_report, markdown_report,
};

use crate::error::AppError;

/// Marker file identifying a RepoDNA output directory.
pub const OUTPUT_MARKER: &str = ".repodna-output";

/// The folder inside a diagnostics bundle (`repodna doctor --export`). Its name appears near
/// the start of the ZIP file, which identifies bundles RepoDNA wrote.
pub const DIAGNOSTICS_FOLDER: &str = "repodna-diagnostics";

/// Text of the marker file.
const MARKER_TEXT: &str = "This directory was generated by RepoDNA. Its files are replaced when reports are regenerated.\n";

/// Bytes inspected when checking whether a file was generated by RepoDNA.
const SNIFF_BYTES: u64 = 64 * 1024;

/// Scale of PNG cards (2 = high density).
const PNG_SCALE: f32 = 2.0;

/// A file to write, relative to an output directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutputFile {
    /// Relative path with `/` separators.
    pub name: String,
    /// Content.
    pub bytes: Vec<u8>,
}

impl OutputFile {
    /// Creates a file from text.
    pub fn text(name: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            bytes: text.into().into_bytes(),
        }
    }
}

fn head(path: &Path) -> Vec<u8> {
    let mut bytes = Vec::new();
    if let Ok(file) = File::open(path) {
        let _ = file.take(SNIFF_BYTES).read_to_end(&mut bytes);
    }
    bytes
}

fn first_line(bytes: &[u8]) -> &[u8] {
    let end = bytes
        .iter()
        .position(|&b| b == b'\n')
        .unwrap_or(bytes.len());
    &bytes[..end]
}

/// Returns `true` when the file at `path` looks like RepoDNA output. `replacement` is the
/// content about to be written; a CSV file whose header row matches it counts as ours.
pub fn generated_by_repodna(path: &Path, replacement: &[u8]) -> bool {
    let bytes = head(path);
    let text = String::from_utf8_lossy(&bytes);
    let markers = [
        "<meta name=\"generator\" content=\"RepoDNA",
        "<!-- repodna-signature",
        GENERATED_MARKER,
        "\"name\": \"RepoDNA\"",
        "\"name\":\"RepoDNA\"",
    ];
    if markers.iter().any(|marker| text.contains(marker))
        || text.contains(&format!("{DIAGNOSTICS_FOLDER}/"))
    {
        return true;
    }
    let is_csv = path
        .extension()
        .is_some_and(|ext| ext.eq_ignore_ascii_case("csv"));
    is_csv && !bytes.is_empty() && first_line(&bytes) == first_line(replacement)
}

fn is_git_root(dir: &Path) -> bool {
    dir.join(".git").exists()
}

/// Joins a `/`-separated relative name onto `dir`, refusing anything that escapes it.
fn contained(dir: &Path, name: &str) -> Result<PathBuf, AppError> {
    let safe = !name.is_empty()
        && !name.starts_with('/')
        && !name.contains('\\')
        && !name.contains(':')
        && name.split('/').all(|part| !part.is_empty() && part != "..");
    if !safe {
        return Err(AppError::internal(format!(
            "refusing to write the unsafe output name `{name}`"
        )));
    }
    Ok(name
        .split('/')
        .fold(dir.to_path_buf(), |path, part| path.join(part)))
}

/// Writes `files` into `dir`, which is created if needed and marked as RepoDNA output.
pub fn write_bundle(
    dir: &Path,
    files: &[OutputFile],
    force: bool,
) -> Result<Vec<PathBuf>, AppError> {
    if dir.exists() {
        if !dir.is_dir() {
            return Err(AppError::input(format!(
                "{} exists and is not a directory",
                dir.display()
            )));
        }
        if is_git_root(dir) {
            return Err(AppError::input(format!(
                "refusing to write reports into {}, the root of a Git working tree",
                dir.display()
            ))
            .with_hint(
                "Choose a separate output directory, for example `--output repodna-report`.",
            ));
        }
        let marked = dir.join(OUTPUT_MARKER).is_file();
        let empty = std::fs::read_dir(dir)
            .map(|mut entries| entries.next().is_none())
            .unwrap_or(false);
        if !marked && !empty && !force {
            return Err(AppError::input(format!(
                "refusing to write into {}: it is not empty and was not created by RepoDNA",
                dir.display()
            ))
            .with_hint(
                "Choose another --output directory, or pass --force to write into it anyway.",
            ));
        }
    }
    std::fs::create_dir_all(dir)
        .map_err(|error| AppError::input(format!("cannot create {}: {error}", dir.display())))?;
    write_atomic(&dir.join(OUTPUT_MARKER), MARKER_TEXT.as_bytes())?;
    let mut written = Vec::new();
    for file in files {
        let path = contained(dir, &file.name)?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| {
                AppError::input(format!("cannot create {}: {error}", parent.display()))
            })?;
        }
        write_atomic(&path, &file.bytes)?;
        written.push(path);
    }
    Ok(written)
}

/// Writes one file the user named. An existing file is replaced only when RepoDNA
/// generated it, or with `force`.
pub fn write_file(path: &Path, bytes: &[u8], force: bool) -> Result<(), AppError> {
    if path.is_dir() {
        return Err(AppError::input(format!(
            "{} is a directory; name a file",
            path.display()
        )));
    }
    if path.exists() && !force && !generated_by_repodna(path, bytes) {
        return Err(AppError::input(format!(
            "refusing to overwrite {}, which was not generated by RepoDNA",
            path.display()
        ))
        .with_hint("Choose another --output path, or pass --force to replace the file."));
    }
    if let Some(parent) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
        std::fs::create_dir_all(parent).map_err(|error| {
            AppError::input(format!("cannot create {}: {error}", parent.display()))
        })?;
    }
    write_atomic(path, bytes)?;
    Ok(())
}

/// A file name for a portable artifact, e.g. `repodna-widget-2026-09-24.repodna`.
pub fn artifact_file_name(dna: &RepositoryDna) -> String {
    let name: String = dna
        .identity
        .name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect();
    let name = name.trim_matches(|c| c == '-' || c == '.');
    let name = if name.is_empty() { "repository" } else { name };
    format!(
        "repodna-{name}-{}.repodna",
        dna.analysis_metadata.generated_at.date_string()
    )
}

/// Renders the Project DNA card.
pub fn card_svg(dna: &RepositoryDna, dark: bool, branding: bool) -> String {
    render_card(dna, CardOptions { dark, branding })
}

/// Renders the Project DNA card as PNG.
pub fn card_png(dna: &RepositoryDna, dark: bool, branding: bool) -> Result<Vec<u8>, AppError> {
    Ok(render_png(&card_svg(dna, dark, branding), PNG_SCALE)?)
}

/// The files of a full report bundle: the HTML report (`index.html`), Markdown, the
/// artifact, the DNA card as SVG and PNG, and CSV tables.
pub fn report_bundle(
    dna: &RepositoryDna,
    options: &ReportOptions,
) -> Result<Vec<OutputFile>, AppError> {
    let dark = options.theme == ReportTheme::Dark;
    let shared = repodna_report::apply_privacy(dna, options.privacy);
    let mut files = vec![
        OutputFile::text("index.html", html_report(dna, options)),
        OutputFile::text("report.md", markdown_report(dna, options)),
        OutputFile::text("repodna.json", json_report(dna, options.privacy, true)?),
        OutputFile::text("dna-card.svg", card_svg(&shared, dark, options.branding)),
        OutputFile {
            name: "dna-card.png".to_owned(),
            bytes: card_png(&shared, dark, options.branding)?,
        },
    ];
    for table in CsvTable::ALL {
        files.push(OutputFile::text(
            format!("data/{}.csv", table.id()),
            csv(&shared, table),
        ));
    }
    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;
    use repodna_core::model::identity::RepositoryIdentity;
    use repodna_core::model::metadata::AnalysisMetadata;

    fn dna() -> RepositoryDna {
        RepositoryDna::new(
            RepositoryIdentity {
                name: "My Widget!".into(),
                ..RepositoryIdentity::default()
            },
            AnalysisMetadata::default(),
        )
    }

    #[test]
    fn writes_bundles_only_where_safe() {
        let root = tempfile::tempdir().unwrap();
        let out = root.path().join("report");
        let files = report_bundle(&dna(), &ReportOptions::default()).unwrap();
        let names: Vec<&str> = files.iter().map(|f| f.name.as_str()).collect();
        assert!(names.contains(&"index.html"));
        assert!(names.contains(&"data/findings.csv"));
        let written = write_bundle(&out, &files, false).unwrap();
        assert_eq!(written.len(), files.len());
        assert!(out.join(OUTPUT_MARKER).is_file());
        // Regenerating into a marked directory is allowed.
        write_bundle(&out, &files, false).unwrap();

        let user = root.path().join("user");
        std::fs::create_dir_all(&user).unwrap();
        std::fs::write(user.join("notes.txt"), "mine").unwrap();
        let refused = write_bundle(&user, &files, false).unwrap_err();
        assert_eq!(refused.exit_code(), 3);
        write_bundle(&user, &files[..1], true).unwrap();
        assert_eq!(
            std::fs::read_to_string(user.join("notes.txt")).unwrap(),
            "mine"
        );

        let git = root.path().join("repo");
        std::fs::create_dir_all(git.join(".git")).unwrap();
        assert!(write_bundle(&git, &files, true).is_err());
        assert!(contained(&out, "../escape").is_err());
        assert!(contained(&out, "/abs").is_err());
    }

    #[test]
    fn replaces_only_generated_files() {
        let root = tempfile::tempdir().unwrap();
        let html = html_report(&dna(), &ReportOptions::default());
        let target = root.path().join("out/report.html");
        write_file(&target, html.as_bytes(), false).unwrap();
        write_file(&target, html.as_bytes(), false).unwrap();

        let mine = root.path().join("index.html");
        std::fs::write(&mine, "<html>my page</html>").unwrap();
        assert!(write_file(&mine, html.as_bytes(), false).is_err());
        write_file(&mine, html.as_bytes(), true).unwrap();

        let table = csv(&dna(), CsvTable::Findings);
        let csv_path = root.path().join("findings.csv");
        std::fs::write(&csv_path, &table).unwrap();
        assert!(generated_by_repodna(&csv_path, table.as_bytes()));
        std::fs::write(&csv_path, "name,value\n").unwrap();
        assert!(!generated_by_repodna(&csv_path, table.as_bytes()));

        let card = card_svg(&dna(), false, true);
        let card_path = root.path().join("card.svg");
        std::fs::write(&card_path, &card).unwrap();
        assert!(generated_by_repodna(&card_path, card.as_bytes()));
        assert!(write_file(root.path(), b"x", true).is_err());
    }

    #[test]
    fn names_portable_artifacts() {
        let mut dna = dna();
        dna.analysis_metadata.generated_at =
            repodna_core::time::Timestamp::from_unix(1_790_000_000);
        assert_eq!(
            artifact_file_name(&dna),
            "repodna-my-widget-2026-09-21.repodna"
        );
    }
}
