// Generates src/generated.ts from the published artifact JSON Schema.
// `--check` fails instead of writing when the committed file is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(here, "../../../schemas/repodna-artifact.schema.json");
const outputPath = join(here, "../src/generated.ts");
const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

const banner = `// Generated by packages/schema/scripts/generate.mjs from
// schemas/repodna-artifact.schema.json. Do not edit by hand: run \`npm run generate -w @repodna/schema\`.
/* eslint-disable */
`;

const types = await compile(schema, "RepositoryDna", {
  bannerComment: banner,
  additionalProperties: false,
  unreachableDefinitions: true,
  strictIndexSignatures: true,
  format: true,
  style: { printWidth: 100, trailingComma: "all" },
});

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== types) {
    console.error("src/generated.ts is out of date: run `npm run generate -w @repodna/schema`.");
    process.exit(1);
  }
  console.log("src/generated.ts is up to date.");
} else {
  writeFileSync(outputPath, types);
  console.log(`Wrote ${outputPath}`);
}
