//! Reports generated from RepoDNA artifacts.
//!
//! Every report is built from a [`RepositoryDna`] artifact alone, so reports can be
//! regenerated later, on another machine, and without the analyzed repository. Privacy
//! presets are applied before anything is rendered.
//!
//! [`RepositoryDna`]: repodna_core::model::artifact::RepositoryDna

pub mod badge;
pub mod card;
pub mod charts;
pub mod ci;
pub mod compare;
pub mod content;
pub mod csv;
pub mod doc;
pub mod error;
pub mod facts;
pub mod fonts;
pub mod html;
pub mod markdown;
pub mod onboarding;
pub mod palette;
pub mod png;
pub mod privacy;
pub mod report;
pub mod sections;
pub mod text;

/// Comment embedded in generated SVG cards and badges, so they can be recognized (for
/// example, to allow regenerating them in place).
pub const GENERATED_MARKER: &str = "<!-- Generated by RepoDNA -->";

pub use compare::{Comparison, compare};
pub use csv::{CsvTable, csv};
pub use error::ReportError;
pub use onboarding::{BundleFile, onboarding_bundle};
pub use privacy::apply_privacy;
pub use report::{PROJECT_URL, ReportOptions, html_report, json_report, markdown_report};
pub use sections::{Section, SectionSet};
