//! The developer onboarding bundle: a small set of Markdown files a newcomer can read
//! in order.

use repodna_core::config::PrivacyPreset;
use repodna_core::model::artifact::RepositoryDna;

use crate::content::{ContentOptions, section};
use crate::doc::Blocks;
use crate::markdown;
use crate::privacy::apply_privacy;
use crate::sections::Section;

/// One file of the bundle.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleFile {
    /// File name within the bundle directory.
    pub name: &'static str,
    /// Title used in the index.
    pub title: &'static str,
    /// Markdown content.
    pub content: String,
}

fn render(dna: &RepositoryDna, sections: &[Section]) -> String {
    let mut blocks = Blocks::default();
    for selected in sections {
        blocks
            .0
            .extend(section(dna, *selected, ContentOptions::default()).0);
    }
    markdown::render(&blocks)
}

/// Builds the onboarding bundle with the given privacy preset applied.
pub fn onboarding_bundle(dna: &RepositoryDna, privacy: PrivacyPreset) -> Vec<BundleFile> {
    let dna = apply_privacy(dna, privacy);
    let parts: [(&'static str, &'static str, &[Section]); 7] = [
        (
            "01-overview.md",
            "Overview and first look",
            &[Section::Summary, Section::Identity],
        ),
        ("02-setup.md", "Setting up and building", &[Section::Build]),
        (
            "03-architecture.md",
            "How the code is organized",
            &[Section::Structure, Section::Architecture],
        ),
        (
            "04-important-files.md",
            "Where to start reading",
            &[Section::Onboarding],
        ),
        ("05-testing.md", "Running the tests", &[Section::Tests]),
        (
            "06-dependencies.md",
            "Dependencies",
            &[Section::Dependencies],
        ),
        (
            "07-recent-changes.md",
            "What changed recently",
            &[Section::TimeMachine],
        ),
    ];
    let mut files: Vec<BundleFile> = parts
        .iter()
        .map(|(name, title, sections)| BundleFile {
            name,
            title,
            content: format!("# {title}\n\n{}", render(&dna, sections)),
        })
        .collect();
    let mut index = format!(
        "# Onboarding: {}\n\nGenerated by RepoDNA {} from revision {} on {}. Read the files in order; every statement comes from the analysis artifact, and detected commands have not been run.\n\n",
        dna.identity.name,
        dna.tool.version,
        dna.analysis_metadata
            .revision
            .as_deref()
            .map_or("(unknown)", |r| &r[..r.len().min(12)]),
        dna.analysis_metadata.generated_at.date_string(),
    );
    for (position, file) in files.iter().enumerate() {
        index.push_str(&format!(
            "{}. [{}]({})\n",
            position + 1,
            file.title,
            file.name
        ));
    }
    index.push_str("\nTerminology used in the code base is collected in the glossary at the end of the file on where to start reading.\n");
    files.insert(
        0,
        BundleFile {
            name: "README.md",
            title: "Onboarding",
            content: index,
        },
    );
    files
}

#[cfg(test)]
mod tests {
    use super::*;
    use repodna_core::model::identity::RepositoryIdentity;
    use repodna_core::model::metadata::AnalysisMetadata;

    #[test]
    fn builds_an_ordered_bundle() {
        let dna = RepositoryDna::new(
            RepositoryIdentity {
                name: "widget".into(),
                ..RepositoryIdentity::default()
            },
            AnalysisMetadata::default(),
        );
        let files = onboarding_bundle(&dna, PrivacyPreset::Share);
        let names: Vec<&str> = files.iter().map(|f| f.name).collect();
        assert_eq!(names[0], "README.md");
        assert_eq!(names.len(), 8);
        assert!(
            files[0]
                .content
                .contains("1. [Overview and first look](01-overview.md)")
        );
        assert!(files[2].content.starts_with("# Setting up and building"));
        assert!(files.iter().all(|f| !f.content.is_empty()));
    }
}
