//! Full reports: JSON, Markdown, and HTML.

use repodna_core::config::{PrivacyPreset, ReportConfig, ReportTheme};
use repodna_core::model::artifact::RepositoryDna;

use crate::content::{ContentOptions, report, signature};
use crate::doc::Inline;
use crate::html::{self, Page};
use crate::privacy::apply_privacy;
use crate::sections::SectionSet;
use crate::{ReportError, markdown};

/// The project's home page, used in generator lines.
pub const PROJECT_URL: &str = "https://github.com/sanskarIN/RepoDNA";

/// How a full report is produced.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReportOptions {
    /// HTML theme.
    pub theme: ReportTheme,
    /// Show "Made by the Sanskar" branding.
    pub branding: bool,
    /// Sections to include.
    pub sections: SectionSet,
    /// Privacy preset applied before rendering.
    pub privacy: PrivacyPreset,
}

impl Default for ReportOptions {
    fn default() -> Self {
        Self {
            theme: ReportTheme::Professional,
            branding: true,
            sections: SectionSet::all(),
            privacy: PrivacyPreset::Local,
        }
    }
}

impl ReportOptions {
    /// Options from the `[report]` configuration table.
    pub fn from_config(config: &ReportConfig) -> Result<Self, ReportError> {
        Ok(Self {
            theme: config.theme,
            branding: config.branding,
            sections: SectionSet::parse(&config.sections).map_err(ReportError::Options)?,
            privacy: config.privacy,
        })
    }
}

fn generator_line(dna: &RepositoryDna, branding: bool) -> Vec<Inline> {
    let mut line = vec![
        Inline::Text("Generated by ".to_owned()),
        Inline::Link {
            text: "RepoDNA".to_owned(),
            url: PROJECT_URL.to_owned(),
        },
        Inline::Text(format!(
            " {} on {}.",
            dna.tool.version,
            dna.analysis_metadata.generated_at.date_string()
        )),
    ];
    if branding {
        line.push(Inline::Text(" Made by the Sanskar.".to_owned()));
    }
    line
}

/// The artifact as JSON after applying the privacy preset.
pub fn json_report(
    dna: &RepositoryDna,
    privacy: PrivacyPreset,
    pretty: bool,
) -> Result<String, ReportError> {
    let dna = apply_privacy(dna, privacy);
    let mut json = if pretty {
        serde_json::to_string_pretty(&dna)?
    } else {
        serde_json::to_string(&dna)?
    };
    json.push('\n');
    Ok(json)
}

/// The full report as Markdown.
pub fn markdown_report(dna: &RepositoryDna, options: &ReportOptions) -> String {
    let dna = apply_privacy(dna, options.privacy);
    let blocks = report(&dna, options.sections, ContentOptions::default());
    let mut out = markdown::render(&blocks);
    out.push_str("---\n\n");
    out.push_str(&markdown::inline(&generator_line(&dna, options.branding)));
    out.push_str("\n\n");
    let compact: serde_json::Value = serde_json::from_str(&signature(&dna)).unwrap_or_default();
    out.push_str(&format!(
        "<!-- repodna-signature {} -->\n",
        compact.to_string().replace("--", "- -")
    ));
    out
}

/// The full report as a self-contained HTML page.
pub fn html_report(dna: &RepositoryDna, options: &ReportOptions) -> String {
    let dna = apply_privacy(dna, options.privacy);
    let blocks = report(
        &dna,
        options.sections,
        ContentOptions {
            figures: true,
            dark: options.theme == ReportTheme::Dark,
            branding: options.branding,
        },
    );
    html::render(
        &blocks,
        &Page {
            title: format!("{} — Project DNA · RepoDNA", dna.identity.name),
            theme: options.theme,
            footer: generator_line(&dna, options.branding),
            signature: signature(&dna),
            version: dna.tool.version.clone(),
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sections::Section;
    use repodna_core::model::SectionStatus;
    use repodna_core::model::git::ContributorRecord;
    use repodna_core::model::identity::RepositoryIdentity;
    use repodna_core::model::metadata::AnalysisMetadata;
    use repodna_core::time::Timestamp;

    fn artifact() -> RepositoryDna {
        let mut dna = RepositoryDna::new(
            RepositoryIdentity {
                name: "widget".into(),
                ..RepositoryIdentity::default()
            },
            AnalysisMetadata::default(),
        );
        dna.git.status = SectionStatus::Analyzed;
        dna.git.contributors = vec![ContributorRecord {
            id: "c-1".into(),
            name: "Ana Example".into(),
            commits: 4,
            insertions: 1,
            deletions: 0,
            first_commit: Timestamp::UNIX_EPOCH,
            last_commit: Timestamp::UNIX_EPOCH,
            active_days: 1,
            areas: Vec::new(),
        }];
        dna
    }

    #[test]
    fn renders_every_format_with_branding_control() {
        let dna = artifact();
        let options = ReportOptions::default();
        let markdown = markdown_report(&dna, &options);
        assert!(markdown.starts_with("# widget — Project DNA"));
        assert!(markdown.contains("Made by the Sanskar."));
        assert!(markdown.contains("<!-- repodna-signature {"));
        let html = html_report(&dna, &options);
        assert!(html.contains("<title>widget — Project DNA · RepoDNA</title>"));
        assert!(html.contains("Made by the Sanskar."));
        let plain = ReportOptions {
            branding: false,
            ..ReportOptions::default()
        };
        assert!(!markdown_report(&dna, &plain).contains("Made by the Sanskar"));
        assert!(!html_report(&dna, &plain).contains("Made by the Sanskar"));
        let json = json_report(&dna, PrivacyPreset::Local, false).unwrap();
        assert!(json.contains("Ana Example"));
    }

    #[test]
    fn applies_privacy_and_section_selection() {
        let dna = artifact();
        let options = ReportOptions {
            privacy: PrivacyPreset::Public,
            sections: SectionSet::parse(&["contributors"]).unwrap(),
            ..ReportOptions::default()
        };
        let markdown = markdown_report(&dna, &options);
        assert!(markdown.contains("## Contributor analytics"));
        assert!(!markdown.contains("## Executive summary"));
        assert!(markdown.contains("Contributor 1"));
        assert!(!markdown.contains("Ana Example"));
        assert!(!html_report(&dna, &options).contains("Ana Example"));
        assert!(
            !json_report(&dna, PrivacyPreset::Public, true)
                .unwrap()
                .contains("Ana Example")
        );
        let config = ReportConfig {
            sections: vec!["nope".into()],
            ..ReportConfig::default()
        };
        assert!(ReportOptions::from_config(&config).is_err());
        assert!(Section::ALL.len() > 20);
    }
}
